<?php

use App\Http\Controllers\Api\V1\AccountController;
use App\Http\Controllers\Api\V1\ActivityCategoryController;
use App\Http\Controllers\Api\V1\ActivityChatController;
use App\Http\Controllers\Api\V1\ActivityController;
use App\Http\Controllers\Api\V1\ActivityInvitationController;
use App\Http\Controllers\Api\V1\ActivityLifecycleController;
use App\Http\Controllers\Api\V1\ActivityParticipationController;
use App\Http\Controllers\Api\V1\ActivityRecurrenceController;
use App\Http\Controllers\Api\V1\ActivitySocialController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BlockController;
use App\Http\Controllers\Api\V1\ClanActivityController;
use App\Http\Controllers\Api\V1\ClanAnnouncementController;
use App\Http\Controllers\Api\V1\ClanController;
use App\Http\Controllers\Api\V1\ClanMessageController;
use App\Http\Controllers\Api\V1\ClanRoleController;
use App\Http\Controllers\Api\V1\ConversationController;
use App\Http\Controllers\Api\V1\EmailVerificationController;
use App\Http\Controllers\Api\V1\FriendController;
use App\Http\Controllers\Api\V1\FriendRequestController;
use App\Http\Controllers\Api\V1\GroupConversationController;
use App\Http\Controllers\Api\V1\MediaController;
use App\Http\Controllers\Api\V1\MessageController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\NotificationPreferenceController;
use App\Http\Controllers\Api\V1\OAuthController;
use App\Http\Controllers\Api\V1\OnboardingController;
use App\Http\Controllers\Api\V1\PasswordController;
use App\Http\Controllers\Api\V1\PresenceController;
use App\Http\Controllers\Api\V1\ProfileController;
use App\Http\Controllers\Api\V1\PushDeviceController;
use App\Http\Controllers\Api\V1\ReadinessController;
use App\Http\Controllers\Api\V1\ReportController;
use App\Http\Controllers\Api\V1\SessionController;
use App\Http\Controllers\Api\V1\StoryController;
use App\Http\Controllers\Api\V1\SportController;
use App\Http\Controllers\Api\V1\UserSportProfileController;
use App\Http\Controllers\Api\V1\UserActivityHistoryController;
use App\Http\Controllers\Api\V1\UserController;
use App\Http\Controllers\Api\V1\VenueController;
use App\Http\Middleware\EnsureIdempotent;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('/ready', ReadinessController::class)->middleware('throttle:60,1');

    Route::middleware('throttle:auth')->group(function (): void {
        Route::post('/auth/register', [AuthController::class, 'register']);
        Route::post('/auth/login', [AuthController::class, 'login']);
        Route::post('/auth/forgot-password', [PasswordController::class, 'forgot']);
        Route::post('/auth/reset-password', [PasswordController::class, 'reset']);
        Route::post('/auth/oauth/{provider}', [OAuthController::class, 'login'])
            ->whereIn('provider', ['google', 'facebook']);
    });

    Route::middleware(['auth:sanctum', 'throttle:api', EnsureIdempotent::class])->group(function (): void {
        Route::get('/auth/me', [AuthController::class, 'me']);
        Route::get('/onboarding', [OnboardingController::class, 'show']);
        Route::put('/onboarding', [OnboardingController::class, 'update']);
        Route::get('/sports', [SportController::class, 'index']);
        Route::get('/users/me/sports', [UserSportProfileController::class, 'index']);
        Route::put('/users/me/sports', [UserSportProfileController::class, 'sync']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::post('/auth/logout-all', [AuthController::class, 'logoutAll']);
        Route::post('/auth/email/verification-notification', [EmailVerificationController::class, 'resend'])
            ->middleware('throttle:6,1');
        Route::get('/auth/email/verify/{id}/{hash}', [EmailVerificationController::class, 'verify'])
            ->middleware(['signed', 'throttle:6,1'])
            ->name('verification.verify');
        Route::patch('/users/me', [ProfileController::class, 'update']);
        Route::patch('/users/me/password', [PasswordController::class, 'change']);
        Route::delete('/users/me', [AccountController::class, 'destroy']);
        Route::get('/auth/sessions', [SessionController::class, 'index']);
        Route::delete('/auth/sessions/{token}', [SessionController::class, 'destroy']);
        Route::get('/stories', [StoryController::class, 'index']);
        Route::post('/stories', [StoryController::class, 'store']);
        Route::post('/stories/{story}/view', [StoryController::class, 'view']);
        Route::get('/stories/{story}/viewers', [StoryController::class, 'viewers']);
        Route::delete('/stories/{story}', [StoryController::class, 'destroy']);
        Route::get('/auth/oauth/accounts', [OAuthController::class, 'accounts']);
        Route::post('/auth/oauth/{provider}/link', [OAuthController::class, 'link'])
            ->whereIn('provider', ['google', 'facebook']);
        Route::delete('/auth/oauth/{provider}', [OAuthController::class, 'unlink'])
            ->whereIn('provider', ['google', 'facebook']);
        Route::get('/users', [UserController::class, 'index']);
        Route::get('/users/suggestions', [UserController::class, 'suggestions']);
        Route::get('/users/me/activity-history', [UserActivityHistoryController::class, 'index']);
        Route::get('/activity-categories', [ActivityCategoryController::class, 'index']);
        Route::get('/activity-categories/{activityCategory}/topics', [ActivityCategoryController::class, 'topics']);
        Route::get('/venues', [VenueController::class, 'index']);
        Route::get('/explore', [ActivityController::class, 'index']);
        Route::get('/activities', [ActivityController::class, 'index']);
        Route::post('/activities', [ActivityController::class, 'store']);
        Route::patch('/activities/{activity}', [ActivityController::class, 'update']);
        Route::post('/activities/{activity}/transfer-ownership', [ActivityController::class, 'transfer']);
        Route::post('/activities/{activity}/recurrence', [ActivityRecurrenceController::class, 'store']);
        Route::post('/activities/{activity}/chat', [ActivityChatController::class, 'store']);
        Route::get('/activities/{activity}/chat', [ActivityChatController::class, 'show']);
        Route::post('/activities/{activity}/like', [ActivitySocialController::class, 'like']);
        Route::delete('/activities/{activity}/like', [ActivitySocialController::class, 'unlike']);
        Route::get('/activities/{activity}/comments', [ActivitySocialController::class, 'comments']);
        Route::post('/activities/{activity}/comments', [ActivitySocialController::class, 'comment']);
        Route::delete('/activities/{activity}/comments/{comment}', [ActivitySocialController::class, 'deleteComment']);
        Route::post('/activities/{activity}/hide', [ActivitySocialController::class, 'hide']);
        Route::delete('/activities/{activity}/hide', [ActivitySocialController::class, 'unhide']);
        Route::get('/activities/{activity}/participants', [ActivityParticipationController::class, 'index']);
        Route::post('/activities/{activity}/join', [ActivityParticipationController::class, 'join']);
        Route::post('/activities/{activity}/leave', [ActivityParticipationController::class, 'leave']);
        Route::post('/activities/{activity}/invitations', [ActivityInvitationController::class, 'invite']);
        Route::get('/activities/{activity}/invitations', [ActivityInvitationController::class, 'index']);
        Route::delete('/activities/{activity}/invitations/{invitation}', [ActivityInvitationController::class, 'revokeDirect']);
        Route::post('/activities/{activity}/invitation-secrets', [ActivityInvitationController::class, 'createSecret']);
        Route::delete('/activities/{activity}/invitation-secrets/{token}', [ActivityInvitationController::class, 'revoke']);
        Route::patch('/activities/{activity}/status', [ActivityLifecycleController::class, 'transition']);
        Route::patch('/activities/{activity}/participants/{participant}/accept', [ActivityParticipationController::class, 'accept']);
        Route::patch('/activities/{activity}/participants/{participant}/reject', [ActivityParticipationController::class, 'reject']);
        Route::delete('/activities/{activity}/participants/{participant}', [ActivityParticipationController::class, 'remove']);
        Route::patch('/activities/{activity}/participants/{participant}/attendance', [ActivityParticipationController::class, 'attendance']);
        Route::get('/activities/{activity}', [ActivityController::class, 'show']);
        Route::post('/activity-invitations/{invitation}/accept', [ActivityInvitationController::class, 'accept']);
        Route::post('/activity-invitations/{invitation}/decline', [ActivityInvitationController::class, 'decline']);
        Route::post('/activity-invitations/redeem', [ActivityInvitationController::class, 'redeem']);
        Route::get('/users/{user}', [UserController::class, 'show']);
        Route::get('/clans', [ClanController::class, 'index']);
        Route::post('/clans', [ClanController::class, 'store']);
        Route::get('/clans/{clan}', [ClanController::class, 'show']);
        Route::patch('/clans/{clan}', [ClanController::class, 'update']);
        Route::get('/clans/{clan}/members', [ClanController::class, 'members']);
        Route::post('/clans/{clan}/join', [ClanController::class, 'join']);
        Route::post('/clans/{clan}/leave', [ClanController::class, 'leave']);
        Route::post('/clans/{clan}/invitations', [ClanController::class, 'invite']);
        Route::patch('/clans/{clan}/members/{member}/review', [ClanController::class, 'review']);
        Route::delete('/clans/{clan}/members/{member}', [ClanController::class, 'remove']);
        Route::post('/clans/{clan}/transfer-ownership', [ClanController::class, 'transfer']);
        Route::get('/clans/{clan}/roles', [ClanRoleController::class, 'index']);
        Route::post('/clans/{clan}/roles', [ClanRoleController::class, 'store']);
        Route::patch('/clans/{clan}/roles/{role}', [ClanRoleController::class, 'update']);
        Route::delete('/clans/{clan}/roles/{role}', [ClanRoleController::class, 'destroy']);
        Route::patch('/clans/{clan}/members/{member}/role', [ClanRoleController::class, 'assign']);
        Route::get('/clans/{clan}/activities', [ClanActivityController::class, 'index']);
        Route::get('/clans/{clan}/statistics', [ClanActivityController::class, 'statistics']);
        Route::get('/clans/{clan}/leaderboard', [ClanActivityController::class, 'leaderboard']);
        Route::get('/clans/{clan}/announcements', [ClanAnnouncementController::class, 'index']);
        Route::post('/clans/{clan}/announcements', [ClanAnnouncementController::class, 'store']);
        Route::patch('/clans/{clan}/announcements/{announcement}', [ClanAnnouncementController::class, 'update']);
        Route::delete('/clans/{clan}/announcements/{announcement}', [ClanAnnouncementController::class, 'destroy']);
        Route::get('/clans/{clan}/messages', [ClanMessageController::class, 'index']);
        Route::post('/clans/{clan}/messages', [ClanMessageController::class, 'store']);
        Route::delete('/clans/{clan}/messages/{message}', [ClanMessageController::class, 'destroy']);
        Route::get('/friend-requests', [FriendRequestController::class, 'index']);
        Route::post('/friend-requests', [FriendRequestController::class, 'store']);
        Route::patch('/friend-requests/{friendRequest}/accept', [FriendRequestController::class, 'accept']);
        Route::patch('/friend-requests/{friendRequest}/reject', [FriendRequestController::class, 'reject']);
        Route::patch('/friend-requests/{friendRequest}/cancel', [FriendRequestController::class, 'cancel']);
        Route::get('/friends', [FriendController::class, 'index']);
        Route::delete('/friends/{user}', [FriendController::class, 'destroy']);
        Route::get('/blocks', [BlockController::class, 'index']);
        Route::post('/blocks/{user}', [BlockController::class, 'store']);
        Route::delete('/blocks/{user}', [BlockController::class, 'destroy']);
        Route::get('/notifications', [NotificationController::class, 'index']);
        Route::patch('/notifications/{notification}/read', [NotificationController::class, 'read']);
        Route::post('/notifications/read-all', [NotificationController::class, 'readAll']);
        Route::get('/notification-preferences', [NotificationPreferenceController::class, 'index']);
        Route::put('/notification-preferences', [NotificationPreferenceController::class, 'update']);
        Route::get('/conversations', [ConversationController::class, 'index']);
        Route::post('/conversations/direct', [ConversationController::class, 'direct']);
        Route::post('/conversations/group', [ConversationController::class, 'group']);
        Route::get('/conversations/{conversation}', [ConversationController::class, 'show']);
        Route::patch('/conversations/{conversation}/group', [GroupConversationController::class, 'update']);
        Route::post('/conversations/{conversation}/members', [GroupConversationController::class, 'addMember']);
        Route::patch('/conversations/{conversation}/members/{member}/role', [GroupConversationController::class, 'role']);
        Route::delete('/conversations/{conversation}/members/{member}', [GroupConversationController::class, 'remove']);
        Route::post('/conversations/{conversation}/transfer-ownership/{member}', [GroupConversationController::class, 'transfer']);
        Route::post('/conversations/{conversation}/leave', [GroupConversationController::class, 'leave']);
        Route::get('/conversations/{conversation}/messages', [MessageController::class, 'index']);
        Route::post('/conversations/{conversation}/messages', [MessageController::class, 'store']);
        Route::patch('/conversations/{conversation}/messages/{message}', [MessageController::class, 'update']);
        Route::delete('/conversations/{conversation}/messages/{message}', [MessageController::class, 'destroy']);
        Route::post('/conversations/{conversation}/messages/{message}/reactions', [MessageController::class, 'react']);
        Route::delete('/conversations/{conversation}/messages/{message}/reactions', [MessageController::class, 'unreact']);
        Route::post('/conversations/{conversation}/messages/{message}/read', [MessageController::class, 'read']);
        Route::post('/conversations/{conversation}/typing', [MessageController::class, 'typing']);
        Route::post('/presence/heartbeat', [PresenceController::class, 'heartbeat']);
        Route::delete('/presence', [PresenceController::class, 'offline']);
        Route::get('/presence/{user}', [PresenceController::class, 'show']);
        Route::post('/push-devices', [PushDeviceController::class, 'store']);
        Route::delete('/push-devices/{device}', [PushDeviceController::class, 'destroy']);
        Route::post('/reports', [ReportController::class, 'store'])->middleware('throttle:report');
        Route::get('/media/{media}', [MediaController::class, 'show'])
            ->middleware('signed')
            ->name('media.show');
    });
});
