<?php

namespace Database\Seeders;

use App\Models\Activity;
use App\Models\ActivityCategory;
use App\Models\ActivityParticipant;
use App\Models\ActivityTopic;
use App\Models\Conversation;
use App\Models\ConversationMember;
use App\Models\Message;
use App\Models\MessageMention;
use App\Models\MessageReaction;
use App\Models\MessageRead;
use App\Models\User;
use Illuminate\Database\Seeder;

class ActivitiesAndChatSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::query()->whereIn('email', [
            'demo@squadup.test', 'alice@squadup.test', 'bryan@squadup.test', 'mila@squadup.test',
        ])->get()->keyBy('email');

        if ($users->count() !== 4) {
            $this->call(DemoDataSeeder::class);
            $users = User::query()->whereIn('email', [
                'demo@squadup.test', 'alice@squadup.test', 'bryan@squadup.test', 'mila@squadup.test',
            ])->get()->keyBy('email');
        }

        $demo = $users['demo@squadup.test'];
        $alice = $users['alice@squadup.test'];
        $bryan = $users['bryan@squadup.test'];
        $mila = $users['mila@squadup.test'];

        $activities = [
            $this->activity($demo, 'Badminton After Work', 'sports', 'Badminton', 1, 'open', 8, false, 'Benjakitti Sports Center'),
            $this->activity($alice, 'Saturday Coffee Tasting', 'food-drink', 'Coffee', 3, 'full', 3, false, 'Ari Coffee Lab'),
            $this->activity($bryan, 'Advanced Mountain Hike', 'outdoors', 'Hiking', 6, 'open', 10, true, 'Doi Suthep Trail'),
            $this->activity($mila, 'Old Quarter Photo Walk', 'arts', 'Photography', -7, 'completed', 12, false, 'Hanoi Old Quarter'),
            $this->activity($demo, 'Cancelled Riverside Cycling', 'outdoors', 'Cycling', 8, 'cancelled', 15, false, 'Bang Krachao Pier'),
        ];

        $this->participants($activities[0], [$demo, $alice, $bryan]);
        $this->participants($activities[1], [$alice, $demo, $mila]);
        $this->participants($activities[2], [$bryan, $demo], [$alice]);
        $this->participants($activities[3], [$mila, $demo, $alice], [], true);
        $this->participants($activities[4], [$demo, $bryan]);

        $direct = $this->conversation('direct', $demo, [$demo, $bryan], null, $this->pairKey($demo->id, $bryan->id));
        $group = $this->conversation('group', $alice, [$alice, $demo, $bryan, $mila], 'Weekend Planners');
        $event = $this->conversation('event', $demo, [$demo, $alice, $bryan], 'Badminton After Work', null, $activities[0]);

        $this->seedDirectMessages($direct, $demo, $bryan);
        $this->seedGroupMessages($group, $alice, $demo, $mila);
        $this->seedEventMessages($event, $demo, $alice, $bryan);
    }

    private function activity(User $host, string $title, string $categorySlug, string $topicName, int $dayOffset, string $status, int $capacity, bool $approval, string $location): Activity
    {
        $category = ActivityCategory::query()->where('slug', $categorySlug)->firstOrFail();
        $topic = ActivityTopic::query()->where('category_id', $category->id)->where('name', $topicName)->firstOrFail();
        $startsAt = now()->startOfHour()->addDays($dayOffset)->setHour(18);

        return Activity::query()->updateOrCreate(
            ['host_id' => $host->id, 'title' => $title],
            [
                'category_id' => $category->id, 'topic_id' => $topic->id,
                'description' => "Demo activity for the {$topicName} discovery and participation flows.",
                'starts_at' => $startsAt, 'ends_at' => $startsAt->copy()->addHours(2),
                'timezone' => 'Asia/Bangkok', 'location_name' => $location,
                'location_address' => $location.', Thailand', 'latitude' => 13.7563,
                'longitude' => 100.5018, 'min_participants' => 2, 'max_participants' => $capacity,
                'status' => $status, 'visibility' => 'public', 'allow_waitlist' => true,
                'allow_friend_invitations' => true, 'require_approval' => $approval,
                'allow_join_by_link' => true, 'rules' => ['Be respectful', 'Arrive on time'],
                'equipment_requirements' => 'Bring suitable personal equipment.',
                'notes' => 'Generated by ActivitiesAndChatSeeder.',
            ]
        );
    }

    private function participants(Activity $activity, array $joined, array $requested = [], bool $attended = false): void
    {
        foreach ($joined as $index => $user) {
            ActivityParticipant::query()->updateOrCreate(
                ['activity_id' => $activity->id, 'user_id' => $user->id],
                [
                    'role' => $user->is($activity->host) ? 'host' : 'member',
                    'status' => $attended ? 'attended' : 'joined',
                    'joined_at' => now()->subDays(2)->addMinutes($index),
                    'attendance_marked_at' => $attended ? now()->subDays(6) : null,
                    'attendance_marked_by' => $attended ? $activity->host_id : null,
                ]
            );
        }

        foreach ($requested as $user) {
            ActivityParticipant::query()->updateOrCreate(
                ['activity_id' => $activity->id, 'user_id' => $user->id],
                ['role' => 'member', 'status' => 'requested', 'joined_at' => null]
            );
        }
    }

    private function conversation(string $type, User $creator, array $members, ?string $name = null, ?string $directKey = null, ?Activity $activity = null): Conversation
    {
        $identity = $directKey ? ['direct_key' => $directKey] : ($activity ? ['activity_id' => $activity->id] : ['type' => $type, 'name' => $name]);
        $conversation = Conversation::query()->updateOrCreate($identity, [
            'type' => $type, 'name' => $name, 'description' => 'Seeded conversation for UI and API testing.',
            'direct_key' => $directKey, 'activity_id' => $activity?->id, 'created_by' => $creator->id,
            'last_message_at' => now(),
        ]);

        foreach ($members as $user) {
            ConversationMember::query()->updateOrCreate(
                ['conversation_id' => $conversation->id, 'user_id' => $user->id],
                ['role' => $user->is($creator) ? 'owner' : 'member', 'status' => 'active', 'joined_at' => now()->subDays(4), 'last_read_at' => now()]
            );
        }

        return $conversation;
    }

    private function seedDirectMessages(Conversation $conversation, User $demo, User $bryan): void
    {
        $first = $this->message($conversation, $demo, 'Are you free for badminton tomorrow?');
        $reply = $this->message($conversation, $bryan, 'Yes, I will bring spare rackets.', 'text', null, $first);
        $this->reaction($reply, $demo, '👍');
        $this->read($first, $bryan);
        $this->read($reply, $demo);
    }

    private function seedGroupMessages(Conversation $conversation, User $alice, User $demo, User $mila): void
    {
        $first = $this->message($conversation, $alice, 'Where should we meet this weekend?');
        $location = $this->message($conversation, $demo, 'Let us meet here.', 'location', [
            'latitude' => 13.7563, 'longitude' => 100.5018, 'label' => 'Central Bangkok',
        ], $first);
        $mention = $this->message($conversation, $mila, '@Alice this location works for me.');
        MessageMention::query()->firstOrCreate(['message_id' => $mention->id, 'user_id' => $alice->id]);
        $this->reaction($location, $mila, '❤️');
    }

    private function seedEventMessages(Conversation $conversation, User $demo, User $alice, User $bryan): void
    {
        $first = $this->message($conversation, $demo, 'Court 2 is booked from 6 PM.');
        $this->message($conversation, $alice, 'I may arrive ten minutes early.', 'text', null, $first);
        $this->message($conversation, $bryan, 'I can bring shuttlecocks.');
    }

    private function message(Conversation $conversation, User $sender, string $body, string $type = 'text', ?array $payload = null, ?Message $reply = null): Message
    {
        return Message::query()->updateOrCreate(
            ['conversation_id' => $conversation->id, 'sender_id' => $sender->id, 'body' => $body],
            ['type' => $type, 'payload' => $payload, 'reply_to_id' => $reply?->id, 'created_at' => now()->subMinutes(10), 'updated_at' => now()->subMinutes(10)]
        );
    }

    private function reaction(Message $message, User $user, string $reaction): void
    {
        MessageReaction::query()->firstOrCreate(['message_id' => $message->id, 'user_id' => $user->id, 'reaction' => $reaction]);
    }

    private function read(Message $message, User $user): void
    {
        MessageRead::query()->updateOrCreate(['message_id' => $message->id, 'user_id' => $user->id], ['read_at' => now()]);
    }

    private function pairKey(string $left, string $right): string
    {
        return collect([$left, $right])->sort()->implode('|');
    }
}
